import {
    ArrowDownUp,
    ArrowRight,
    ArrowUp,
    Baby,
    BadgeCheck,
    Bandage,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Clock3,
    Facebook,
    FileText,
    Filter,
    Globe,
    Grid2x2,
    HeartPulse,
    Home,
    IndianRupee,
    Instagram,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Minus,
    PackageSearch,
    Phone,
    Pill,
    Plus,
    Search,
    Send,
    ShieldCheck,
    Sparkles,
    Star,
    Stethoscope,
    Truck,
    Trash2,
    Upload,
    X,
    Droplets,
    ShoppingCart,
    Quote,
    UserRound,
    ExternalLink,
    RefreshCw,
    Play,
    ClipboardList,
} from 'lucide-react';

export const iconMap = {
    ArrowDownUp,
    ArrowRight,
    ArrowUp,
    Baby,
    BadgeCheck,
    Bandage,
    CheckCircle2,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    Clock3,
    Facebook,
    FileText,
    Filter,
    Globe,
    Grid2x2,
    HeartPulse,
    Home,
    IndianRupee,
    Instagram,
    Mail,
    MapPin,
    Menu,
    MessageCircle,
    Minus,
    PackageSearch,
    Phone,
    Pill,
    Plus,
    Search,
    Send,
    ShieldCheck,
    Sparkles,
    Star,
    Stethoscope,
    Truck,
    Trash2,
    Upload,
    X,
    Droplets,
    ShoppingCart,
    Quote,
    UserRound,
    ExternalLink,
    RefreshCw,
    Play,
    ClipboardList,
};

export default function Icon({ name, className = 'h-5 w-5', strokeWidth = 1.75, ...props }) {
    const Component = iconMap[name];

    if (!Component) {
        return null;
    }

    return <Component className={className} strokeWidth={strokeWidth} {...props} />;
}